steps:
  # Build migration image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_TAG', '-f', 'Dockerfile.migrate', '.']
    dir: 'backend'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_TAG']

  # Run migration job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'schema-migrate'
      - '--image=$_TAG'
      - '--region=europe-west2'
      - '--set-cloudsql-instances=$_CLOUD_SQL_CONNECTION'
      - '--set-env-vars=DB_INSTANCE_CONNECTION_NAME=$_CLOUD_SQL_CONNECTION,DB_USER=elite_user,DB_NAME=elite_concierge,DB_PASS=$_DB_PASS'
      - '--execute-now'
      - '--wait'

substitutions:
  _TAG: 'europe-west2-docker.pkg.dev/${PROJECT_ID}/elite-concierge-repo/migrate:${SHORT_SHA}'
  _CLOUD_SQL_CONNECTION: '${PROJECT_ID}:europe-west2:elite-concierge-db'
  _DB_PASS: ''  # Set via --substitutions at runtime

options:
  logging: CLOUD_LOGGING_ONLY
