"""feat(backend): add biometric and insight models for proactive concierge

Revision ID: 22c7ae9794a0
Revises: 890a83956813
Create Date: 2026-03-02 23:08:53.982458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '22c7ae9794a0'
down_revision: Union[str, Sequence[str], None] = '890a83956813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_biometrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=False),
    sa.Column('recovery_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_biometrics_date'), 'daily_biometrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_biometrics_user_id'), 'daily_biometrics', ['user_id'], unique=False)
    op.create_table('daily_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('insight_headline', sa.String(), nullable=False),
    sa.Column('actionable_advice', sa.Text(), nullable=False),
    sa.Column('suggested_plan_override', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_insights_date'), 'daily_insights', ['date'], unique=False)
    op.create_index(op.f('ix_daily_insights_user_id'), 'daily_insights', ['user_id'], unique=False)
    
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.alter_column('document_chunks', 'embedding',
                existing_type=sa.NUMERIC(precision=768),
                type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                existing_nullable=False)
        op.alter_column('session_analysis', 'embedding',
                existing_type=sa.NUMERIC(precision=768),
                type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_analysis', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=False)
    op.drop_index(op.f('ix_daily_insights_user_id'), table_name='daily_insights')
    op.drop_index(op.f('ix_daily_insights_date'), table_name='daily_insights')
    op.drop_table('daily_insights')
    op.drop_index(op.f('ix_daily_biometrics_user_id'), table_name='daily_biometrics')
    op.drop_index(op.f('ix_daily_biometrics_date'), table_name='daily_biometrics')
    op.drop_table('daily_biometrics')
    # ### end Alembic commands ###
