"""feat(auth): add tier and ai_usage_count for paywall

Revision ID: 890a83956813
Revises: 717160050549
Create Date: 2026-03-02 22:00:59.188931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '890a83956813'
down_revision: Union[str, Sequence[str], None] = '717160050549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.alter_column('document_chunks', 'embedding',
                existing_type=sa.NUMERIC(precision=768),
                type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                existing_nullable=False)
        op.alter_column('session_analysis', 'embedding',
                existing_type=sa.NUMERIC(precision=768),
                type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                existing_nullable=False)
    
    # Add columns regardless of dialect (if they don't exist, which autogenerate usually handles)
    # Check if columns exist before adding for robustness on SQLite if needed, 
    # but op.add_column is usually fine if they weren't there.
    op.add_column('users', sa.Column('tier', sa.String(), nullable=False))
    op.add_column('users', sa.Column('ai_usage_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_usage_count')
    op.drop_column('users', 'tier')
    op.alter_column('session_analysis', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=False)
    # ### end Alembic commands ###
