"""feat: add equipment_constraint to user

Revision ID: b3377bbff1f0
Revises: 22c7ae9794a0
Create Date: 2026-03-02 23:42:42.953621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'b3377bbff1f0'
down_revision: Union[str, Sequence[str], None] = '22c7ae9794a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=sa.NUMERIC(precision=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.alter_column('session_analysis', 'embedding',
               existing_type=sa.NUMERIC(precision=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.add_column('users', sa.Column('equipment_constraint', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'equipment_constraint')
    op.alter_column('session_analysis', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=False)
    # ### end Alembic commands ###
